### ISSUE TITLE
Survey/response pages changes

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#181]
See tasks

```[tasklist]
### Tasks
- [x] Change “Observing systems (##)” to “Add/Edit observing systems (##)”
- [x] Change “Data products (##)” to  “Add/Edit Data products (##)”
- [x] Change “Applications (##)” to “Add/Edit Applications (##)”
- [x] Change “Societal Benefit Areas (##)” to “Add/Edit Societal Benefit Areas (##)”
- [ ] https://github.com/nsidc/usaon-benefit-tool/issues/217
- [x] Can we have a different table display for admins vs. respondents/analysts? For admins: keep table fields as is. For respondents/analysts: only display Title, Description, Status, Private, and the edit button.
- [x] Change the "eye" logo to say simply "edit" (once people are assigned to specific surveys, we'll want to differentiate between "view" and "edit")
- [x] If easy, timestamp formats throughout should be YYYY-MM-DD HH:MM (remove seconds and milliseconds)
```

**Comment by mfisher87** [comment]
>add the ability to sort by different fields

I'm pulling this requirement out; it should be its own ticket! @hazel that's #218 . What milestone do you think? I don't think it will be hard, but also not trivial if that helps :)

There are some larger refactors I want to adopt (specifically HTMX) that would really help with features like sorting and deletion, and it may make sense to, for now, think about sensible defaults for sorting and filtering so we can come back to fully customizable sorting and filtering.

**Comment by mfisher87** [comment]
>If easy, timestamp formats throughout should be YYYY-MM-DD HH:MM (remove seconds and milliseconds)

Here! Here! :)

**Comment by mfisher87** [comment]
>If easy, timestamp formats throughout should be YYYY-MM-DD HH:MM (remove seconds and milliseconds)

Setting by default didn't work as I hoped, so I added a convenience function for formatting like this (e.g. `{{ survey.created_timestamp | dateformat}}` in a page template). We'll have to keep an eye out for wrongly formatted dates and apply this change. Not ideal, but we can come back later to see about setting a default date string format.

**Comment by hazelshapiro** [comment]
> > add the ability to sort by different fields
> 
> I'm pulling this requirement out; it should be its own ticket! @hazel that's #218 . What milestone do you think? I don't think it will be hard, but also not trivial if that helps :)
> 
> There are some larger refactors I want to adopt (specifically HTMX) that would really help with features like sorting and deletion, and it may make sense to, for now, think about sensible defaults for sorting and filtering so we can come back to fully customizable sorting and filtering.

Updated #218
