### ISSUE TITLE
Adjust navigation menu for the survey response page

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#192]
```[tasklist]
### Tasks
- [x] Change "response home" to "User Guide"
- [ ] Remove the sankey diagram from response home/user guide page
- [ ] Add generic step 1, step 2, step 3 text to the user guide page so Hazel can add more detail later
- [ ] Delete the "Response to:" in the page header
- [ ] Move the survey ID to the bottom of the page
```

**Comment by mfisher87** [comment]
@hazelshapiro please confirm this looks good. I'm putting v1.4.0 in QA.
