### ISSUE TITLE
Diagram display - quick fixes

### ISSUE THREAD

**Issue by hazelshapiro** [nsidc/usaon-benefit-tool#194]
```[tasklist]
### Tasks
- [x] Change header above each diagram from “U.S. AON Benefit Tool Diagram” to “[project title]”
- [x] Increase font size for object names
- [x] Change hamburger navigation to button that says / uses icon for “Print / Download”
- [x] Change hover text on hamburger from “chart context menu” to “Print and download options”
```

**Comment by Sherwin-14** [comment]
@hazelshapiro  Hey, do you have some considerations regarding font size?

**Comment by hazelshapiro** [comment]
@Sherwin-14 I would simply like to try improving readability. The font size in the Benefit Tool overall is good, but I wanted to try bumping it 2-4 sizes bigger in the diagram to see what that looks like. Does that make sense? I suppose eventually we could consider adding that as something that the user could adjust in the final diagram viewer, but we don't have that page designed yet and I am guessing that we won't get to those kind of options in this round of development. 

Is that helpful?

**Comment by Sherwin-14** [comment]
Thanks, that helps a lot!

**Comment by Sherwin-14** [comment]
Hey , just for reference here survey title means the project name?

**Comment by mfisher87** [comment]
I think this is the text @hazelshapiro is looking to change, is that right?

![image](https://github.com/nsidc/usaon-benefit-tool/assets/3608264/31bc4818-6ed0-411d-a7a4-f09b462603e1)

**Comment by Sherwin-14** [comment]
Ah Yes , but the first objective lists that title of the chart should also be changed. I think survey title here means the project name and just wanted to clarify this.

**Comment by mfisher87** [comment]
We changed the terminology of "Survey" to "Project" in a recent change (https://github.com/nsidc/usaon-benefit-tool/issues/228 - https://github.com/nsidc/usaon-benefit-tool/pull/219), sorry for being unclear on that!

This "Project" on QA is a good example: https://qa.usaon.org/apps/benefit-tool/survey/3

Here, the title of the "Project" is "SIO test", so that's the text we'd want to use for the diagram's title as well.

**Comment by mfisher87** [comment]
I think I haev the last of it in #194
